// Generated by CoffeeScript 1.4.0
(function() {
  "use strict";

  var AMDCompiler, AbstractCompiler,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AbstractCompiler = require("./abstract_compiler");

  AMDCompiler = (function(_super) {

    __extends(AMDCompiler, _super);

    function AMDCompiler() {
      return AMDCompiler.__super__.constructor.apply(this, arguments);
    }

    AMDCompiler.prototype.stringify = function() {
      var args, export_, output, preamble, _i, _len, _ref, _ref1;
      _ref = this.buildPreamble(this.dependencyNames), args = _ref[0], preamble = _ref[1];
      if (this.exports.length !== 0) {
        this.dependencyNames.push('exports');
        args.push('__exports__');
      }
      output = [];
      if (this.moduleName) {
        output.push("define(\"" + this.moduleName + "\",");
      } else {
        output.push("define(");
      }
      this.indent(output);
      output.push("" + (JSON.stringify(this.dependencyNames)) + ",");
      this.emitFunctionHeader(output, args);
      this.indent(output);
      output.push("\"use strict\"" + this.eol);
      output.push.apply(output, preamble);
      output.push.apply(output, this.lines);
      _ref1 = this.exports;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        export_ = _ref1[_i];
        output.push("__exports__." + export_ + " = " + export_ + this.eol);
      }
      if (this.exportAs) {
        output.push("return " + this.exportAs + this.eol);
      }
      this.outdent(output);
      output.push("" + this.functionTail + ")" + this.eol);
      this.outdent(output);
      return this.buildStringFromLines(output);
    };

    return AMDCompiler;

  })(AbstractCompiler);

  module.exports = AMDCompiler;

}).call(this);
