// Generated by CoffeeScript 1.4.0
(function() {
  var CoffeeScript, Compiler, defaultCoffeeHandler, defaultJSHandler, disable, enable, enabled, es6CoffeeRequireHandler, es6JSRequireHandler, fs, loadES6Script, path, vm;

  vm = require('vm');

  fs = require('fs');

  path = require('path');

  Compiler = require('./compiler');

  try {
    CoffeeScript = require('coffee-script');
  } catch (_error) {}

  enabled = false;

  defaultJSHandler = require.extensions['.js'];

  defaultCoffeeHandler = require.extensions['.coffee'];

  enable = function() {
    if (enabled) {
      return;
    }
    enabled = true;
    require.extensions['.js'] = es6JSRequireHandler;
    if (CoffeeScript != null) {
      return require.extensions['.coffee'] = es6CoffeeRequireHandler;
    }
  };

  disable = function() {
    if (!enabled) {
      return;
    }
    enabled = false;
    require.extensions['.js'] = defaultJSHandler;
    if (CoffeeScript != null) {
      return require.extensions['.coffee'] = defaultCoffeeHandler;
    }
  };

  es6JSRequireHandler = function(module, filename) {
    return module._compile(loadES6Script(filename));
  };

  es6CoffeeRequireHandler = function(module, filename) {
    return module._compile(CoffeeScript.compile(loadES6Script(filename)));
  };

  loadES6Script = function(filename) {
    var content, extname;
    content = fs.readFileSync(filename, 'utf8');
    extname = path.extname(filename);
    return new Compiler(content, path.basename(filename, extname), {
      coffee: extname === '.coffee'
    }).toCJS();
  };

  module.exports = {
    enable: enable,
    disable: disable
  };

}).call(this);
